TN = float(input('Vorhergesgt: Falsch, tatsaechlich falsch '))
FN = float(input('Vorhergesagt: Falsch, tatsaechlich richtig '))
FP = float(input('Vorhergesagt: richtig, tasaechlich falsch ' ))
TP = float(input('Vorhergesagt: richtig, tasaechlich richtig '))
N = float(TN + FP)
P = float(FN + TP)
n = TN + FN +  FP + TP

print("\n n = {:^15}| Vorhergesgt: Falsch | Vorhergesagt: richtig | Summe".format(n))
row = "{}|{}|{}|{}".format("-"*20, "-"*21, "-"*23, "-"*10)
print(row)
print("{:^20}|{:^21}|{:^23}|{:^10}".format( "Tatsaechlich Falsch", TN, FP, N))
print("{:^20}|{:^21}|{:^23}|{:^10}".format( "Tatsaechlich richtig", FN, TP, P))
print("{:^20}|{:^21}|{:^23}|{:^10}".format( "Summe", TN + FN, FP + TP, ""))

ACC = round((TP+TN)/(P+N), 2)
Miscl = round((FP+FN)/(P+N), 2)
PPV = round(TP/(TP+FP), 2)
TPR = round(TP/P, 2)
FPR = round(FP/N, 2)
TNR = round(1-FPR, 2)
F1 = round(2 * ((PPV*TPR)/(PPV+TPR)), 2)

print("\nAccuracy (ACC) = {} ".format(ACC))
print("\nMissclassification = {} ".format(Miscl))
print("\nPrecision (PPV) = {}".format(PPV))
print("\nSensitivity (TPR) = {}".format(TPR))
print("\nFall-out (FPR) = {}".format(FPR))
print("\nSpecificity (TNR) = {}".format(TNR))
print("\nF1 = {}\n".format(F1))